#ifndef ROBOT_PARAMETERS_H
#define ROBOT_PARAMETERS_H


#define LIFT_ZERO_BOX 0.5
#define LIFT_ONE_BOX 1.5
#define LIFT_TWO_BOX 2.5
#define LIFT_THREE_BOX 3.5
#define LIFT_FOUR_BOX 4.5
#define LIFT_TOLERANCE 20
#define LOCKS_OPEN false
#define LOCKS_CLOSED true
#define ARMS_CLOSED true
#define ARMS_OPEN false
#define MOVEMENT_DELAY .3
#define JAWS_OPEN false
#define JAWS_CLOSED true

//ENCODER VALUES
#define LIFT_ENCODER_SLOWDOWN_DISTANCE 200
#define BOTTOM_LIMIT_EV 0
#define FIRST_CONTACT_EV 1000
#define TRANSFER_EV 2000
#define INTERFERENCE_LOCKOUT_EV 3000
#define ARM_LOCKOUT_EV 3500
#define TWO_STACK_EV 4000
#define THREE_STACK_EV 5000
#define FOUR_STACK_EV 5000
#define FIVE_STACK_EV 7000
#define SIX_STACK_EV 8000
#define TOP_LIMIT_EV 10000



#define CAMERA_NAME "cam1"


#define CTRLR_HOR_INTAKE_TOLERANCE 0.8
#endif
