#ifndef ROBOT_PARAMETERS_H
#define ROBOT_PARAMETERS_H


#define LIFT_ZERO_BOX 0.5
#define LIFT_ONE_BOX 1.5
#define LIFT_TWO_BOX 2.5
#define LIFT_THREE_BOX 3.5
#define LIFT_FOUR_BOX 4.5
#define LIFT_TOLERANCE 0.2

#define CONTROLLER_HOR_INTAKE_TOLERANCE 0.8
#endif
